# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/appstudio.redhat.com_buildpipelineselectors.yaml

patchesJson6902:
- path: patches/fix-tekton-params.yaml
  target:
    kind: CustomResourceDefinition
    name: buildpipelineselectors.appstudio.redhat.com
